apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: cns
data:
  # base64 encoded password. E.g.: echo -n "mypassword" | base64
  key: M0w1SkRjYWxrVFFLbmZSTUxsTUw2TGJKb0tVVC9qTmp6VVc4VzR1QlF2Yz0=
type: gluster.org/glusterblock
