apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
 annotations:
  storageclass.kubernetes.io/is-default-class: "false"
 name: gluster-block
provisioner: gluster.org/glusterblock
parameters:
 resturl: "http://heketi-cns-cns.apps.openshift.pub"
 restuser: "admin"
 restsecretnamespace: "cns"
 restsecretname: "heketi-secret"
 hacount: "3"
 clusterids: "7d9f0977267ec2ac36a6e744440883bf"
 chapauthenabled: "true"
